### ISSUE TITLE
Use i18n instead of PRODUCT_NAME in all the project

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1018]
### What happened?

Now that we have i18n we should be able to have product specific entries and avoid relying on PRODUCT_NAME

**Comment by lahabana** [comment]
@johncowen I think you did this right?

**Comment by johncowen** [comment]
Oh mostly, yeah, now we are just unfortunately left with the place where we started using `env('KUMA_PRODUCT_NAME')` previous to us having i18n. If you are ok with it, could we add this to the board? Then we can replace all the `env('KUMA_PRODUCT_NAME')`  with `t` usage and then we are done with it. It shouldn't take more than an hr or so.

**Comment by kleinfreund** [comment]
This was done in https://github.com/kumahq/kuma-gui/pull/1383.
