### ISSUE TITLE
The GUI shows the initial wizard when it shouldn't

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma-gui#104]
The GUI shows an initial wizard when the cluster is empty, but in this instance the cluster is not empty **yet** this wizard is being displayed:

<img width="754" alt="Screen Shot 2020-12-09 at 1 52 01 PM" src="https://user-images.githubusercontent.com/964813/101692976-d82d9900-3a25-11eb-883e-99f1b1cf35b3.png">

**Comment by tomaszwylezek** [comment]
It was fixed in https://github.com/kumahq/kuma-gui/pull/202
