### ISSUE TITLE
Re-think policy display dropdown

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-gui#1066]
### Description

Had some feedback from a few places that this isn't a great UX, and I think I agree. We should brainstorm better options here.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we need feedback from design team

**Comment by erickrico** [comment]
Hey early iteration on how we could improve the ui, let me know if this approach makes sense or you see anything missing https://www.loom.com/share/0eee938e77e44679a294708dc9804c6c?sid=56f23e4c-3524-42df-a418-a4d2488305de
