### ISSUE TITLE
fix: Reduce the amount of HTTP requests we make

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1135]
### What happened?

There are certain areas where we make too many HTTP requests, some times unnecessarily repeated HTTP requests, sometimes requests that respond with data that we no longer need (this one is more tech debt), and sometimes we request data too early (i.e. at application bootstrap rather than when we visit the page that needs the data).

We also poll 2 endpoints every 10 seconds for data throughout the lifetime of the application. Some of this data is no longer needed and most of this data should be synced from other HTTP calls rather than relying on polling. We should look to remove the polling when only used for local data syncing.

Possibly related to https://github.com/kumahq/kuma-gui/pull/1122 which is awaiting potential approval. At which point this approach could be rolled out to the rest of the application, probably beginning with finishing up the `policies` area (this is where we use data gained at app bootup), and then rolling it out across all the collection pages first, followed by the detail pages.

Once complete we should preferably no longer be making duplicated HTTP requests and only be requesting data when we need it. Additionally we should try to remove polling to ensure data stays in sync locally, especially polling whilst on pages that don't require the data that we are polling for.

**Comment by lahabana** [comment]
A lot of things have improved here. We should check this once all the datasource stuff has landed

**Comment by lahabana** [comment]
We looked at this. The only ones left is getting rid of the bootstrap and this is covered somewhere else.
