### ISSUE TITLE
rework policy picker to not be a dropdown

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1144]
### Description

The idea explored was a side list:

https://www.figma.com/file/Q5z8lPJeU26763q30S9GTy/MinK?type=design&node-id=1473-35106&mode=design&t=bPAKe928kR4PCSt0-0

**Comment by kleinfreund** [comment]
For reference, the design was updated at some point: https://www.figma.com/file/Q5z8lPJeU26763q30S9GTy/MinK?type=design&node-id=1770-33657&mode=design&t=yiCwgKqGAPnEPcXk-0
