### ISSUE TITLE
Rework overview page

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1145]
### Description

The overview page is currently not really great. We've worked on a redesign which will likely be more useful to users.

https://www.figma.com/file/Q5z8lPJeU26763q30S9GTy/MinK?type=design&node-id=1401-14011&mode=design&t=MatjaB0lxVXsdZF7-0

**Comment by kleinfreund** [comment]
The Kuma GUI side of things will be implemented in https://github.com/kumahq/kuma-gui/pull/1291.

**Comment by jakubdyszkiewicz** [comment]
"soft" blocked on the new APIs

**Comment by kleinfreund** [comment]
The rest of this task will be implemented in https://github.com/kumahq/kuma-gui/pull/1315.

**Comment by kleinfreund** [comment]
Mostly done. Outstanding work tracked in https://github.com/kumahq/kuma-gui/issues/1346.
