### ISSUE TITLE
Add data correction/reshaping in a data layer separate from the view layer

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1264]
### Description

1. Move data reshaping/logic type functions over to a "data layer". These should be within a `module-name/data` folder (for a rough example see https://github.com/kumahq/kuma-gui/tree/467e78de210f481c2b47d4002d1d1a357838f6d9/src/app/zones/data)
2. Avoid undefined/null arrays and potentially objects. What to do with arrays is clearer, objects could be less clear, see accompanying MADR on the overall approach for guidance. For other primitive values again try to use best judgement using the MADR for guidance. (for a rough example see https://github.com/kumahq/kuma-gui/blob/467e78de210f481c2b47d4002d1d1a357838f6d9/src/app/zone-ingresses/data/index.ts)
3. Refactor and combine above data reshaping/logic type functions so we are reusing what we can. What exactly this involves will depend on lots of things and will be case by case.
4. Move as many calls to these "data layer" functions into the `sources.ts` files, so the data is reshaped as soon as we receive it.

Depending on the situation the above can be done in a different order depending on the module/whatever is easiest and don't have to all be in the same PR.

- [x] DataPlanes
  - #1871
  - #1909
  - #1908
- [x] ControlPlanes
  - #1914
- [x] Diagnostics
  - #1914
- [x] Onboarding (has no data sources)
- [ ] Subscriptions
  - https://github.com/kumahq/kuma-gui/pull/1915
- [x] Meshes
  - #1912
- [x] Policies
  - #1888
- [x] Services
  - #1886
- [x] Zone Egresses
  - https://github.com/kumahq/kuma-gui/pull/1869
- [x] Zone Ingresses
  - https://github.com/kumahq/kuma-gui/pull/1867
- [x] Zones 
  - https://github.com/kumahq/kuma-gui/pull/1854
- [ ] Final review incase there are any stray bits or missed bit once the above list of modules is complete.

**Comment by lahabana** [comment]
Let's do that on a per module basis

**Comment by johncowen** [comment]
I updated the description here and included a rough approach plus a list of modules we'll need to cover. We can use that to track progress.
