### ISSUE TITLE
Switch to use of mesh-insights in Overview

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-gui#127]
Currently we are sending requests to multiple endpoints to get the data which we are displaying on the Overview (counters of resources, charts).

There is a better way and we should use the [mesh insights](https://kuma.io/docs/latest/documentation/http-api/#mesh-insights) endpoint which includes most of data we need, without unnecessary ones

**Comment by tharun208** [comment]
this is also closed by this pr - https://github.com/kumahq/kuma-gui/pull/133

**Comment by tomaszwylezek** [comment]
Closing as it was resolved in #133
