### ISSUE TITLE
Improve chart labels edge cases behaviour/look

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-gui#130]
As charts will have the labels inside the charts (ref: #129), currently there was no work done, to make sure that the charts will look fine if there will be not enough space for the label to fully be visible in the chart

My current idea is to place the label outside the chart if there is not enough space for it, and if there will be too many labels, which could overlap between each other, we could think about maybe introducing legend or something else.

Overall, there needs to be done some work to improve this.

**Comment by jakubdyszkiewicz** [comment]
> Triage: @bartsmykla can you elaborate? Is the issue still present?
