### ISSUE TITLE
Update mock for rest server after introducing mesh-insights

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-gui#131]
For test purposes, when doing `npm run serve` we are mocking some of the api endpoints, to see how the GUI will behave. After introducing mesh-insights in place of many different requests in Overview, we stopped using and displaying mock data.

To fix/update it, we have to introduce another endpoint/s for mesh-insights in our mock implementations

**Comment by tomaszwylezek** [comment]
The mock is already provided, closing.
