### ISSUE TITLE
KLoader has issue where progress can exceed 100

### ISSUE THREAD

**Issue by darrenjennings** [kumahq/kuma-gui#135]
I noticed that the KLoader is using a copied version of an old component. We moved the Full screen loader to a kongponent (which resolves the >100 progress bug):

https://github.com/Kong/kongponents/blob/master/packages/KSkeleton/FullScreenKongSkeleton.vue#L54
https://github.com/kumahq/kuma-gui/blob/master/src/components/KLoader.vue#L43

Possible solution is that the KLoader can receive an asset name so that the assets can be customized so you could pass `../assets/images/kuma-loader-v1.gif?external` to KSkeleton, and then have kuma-gui use the kskeleton kongponent.

**Comment by tomaszwylezek** [comment]
It was fixed in #187 and merged into kuma in kumahq/kuma#2481
