### ISSUE TITLE
Represent available services in Zone Ingress details

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#1388]
To do:

- Zone Ingress: Represent available services

Done:

- Zone Ingress: Represent networking information
- Zone Egress: Represent networking information

**Comment by johncowen** [comment]
We had a quick chat about this, for an initial build of this we should probably add a [Services] tab to the Zone ingress detail view and add a table/AppCollection with the information we get from the zone-ingress `availableServices` data.

Later on we could move this around, but this would be a good start.
