### ISSUE TITLE
Data Plane Proxies show only first service/zone from tags

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#1407]
### What happened?

When we show tags for Data Plane Proxies (both list and detail views), we only read the first service and zone from the annotations even though there could be multiple.

How do we want to handle this?

**Comment by jakubdyszkiewicz** [comment]
> Triage: @kleinfreund to reach out to design to ask. We could list all services in one cell separated by the new line

**Comment by lahabana** [comment]
There are places in the Konnect UI that show multiple entries and an ellipsis to make things still compact. Is this what we should do here?
