### ISSUE TITLE
cleanup: Remove Vuex

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1453]
### Description

We are at the point where we have very little need for a global state store, and much of the code that was in Vuex has now gone.

We should continue to remove the last little bits of Vuex code (mainly onboarding) and then remove Vuex entirely.

If we need any sort of frontend state in the future we should use either:

1. The URL
2. LocalStorage
3. Shared JS vars
4. provide/inject
5. Pinia (please reach out to discuss if we think need to install this)

The choice of above would depend on the use case. 

We should continue to avoid maintaining a separate source of truth to the single source of truth in the backend.

**Comment by johncowen** [comment]
This is mostly done, but we still have the Vuex store "stub" for integration reasons, we should move it out of here, should be a low effort task now.

**Comment by lahabana** [comment]
Our latest understanding is that we no longer us the store and we should be able to remove vuex now. @johncowen is this your understanding too?

**Comment by lahabana** [comment]
Sounds like we can remove the dependency from here as soon as we can make vue plugins loaded conditionally so that entreprise can still use vuex

**Comment by johncowen** [comment]
Related: https://github.com/kumahq/kuma-gui/pull/1569

The above PR adds a `$.plugins` label, that then automatically gets picked up by Vue, and the labelled plugins are then added to Vue. Previous to the above PR the "adding the store as a plugin" was hardcoded into the kuma codebase.

With the above PR, it is no longer hardcoded and instead added via labels, which means its easier to add/remove from another project (ie without having it hardcoded into the kuma codebase)
