### ISSUE TITLE
DataSource improvements

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1474]
### Description

This one is a bit of an umbrella issue, happy to split up if thats what we want to do.

1. Make helper for `source.ts` files such as in order to return 'EventSources' from the `source.ts` files instead of automatically wrapping promises behind the scenes. Example:
```javascript
(params) => {
  return source(() => {
    return anyOldPromiseReturningClient('/api/url')
  }, {
    options
  })
}
```

Ideally we should still be able to return promises to get a simple 1 time message event.

2. Add `src` or `uri` helper instead of JS templates to use in the DataSource component:
```javascript
<DataSource 
  :src="src(
    '/meshes/:mesh/service/:name',
    {
       mesh: route.params.mesh,
       name: route.params.dataPlane
    }
  )"
>
```

`src` should check that the parameters of the 2nd params object aren't `undefined`

**Comment by lahabana** [comment]
1 has been done 2 needs to happen after: [#1817](https://github.com/kumahq/kuma-gui/issues/1817)

**Comment by johncowen** [comment]
1 here was done a while back, I've split point 2 into a separate issue here https://github.com/kumahq/kuma-gui/issues/2432.

Closing this one.
