### ISSUE TITLE
Implement basic e2e tests against a real API

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1535]
### Description

Ideally should involve bringing up a real kuma and setting that up ready for testing against.

Worth noting that these can (probably/possibly should) be minimal tests on API endpoints etc and ideally we can also run the same tests against our mocks. (very much my opinion this bit so very much open to discussion)

P.S. I'd always wondered about auto-generating our mocks from OpenApi specs but also all we need to really test is that our mock API is correct. I'd almost rather these tests concentrated on that 🤔 

We also have to be careful here as ideally we don't want to test what we don't own.

**Comment by lahabana** [comment]
Let's have a general discussion about whether or not we should do this or if the value added is too low.

**Comment by lahabana** [comment]
Maybe one day
