### ISSUE TITLE
Presentation view of dataplane envoy info

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1556]
### Description

Here's an example output of all the things we can get for a dpp: https://gist.github.com/lahabana/651895bd22ace1e8f59d00c291340e26

The goal of this issue is to make the data from these pages useful to non envoy experts.
With all this data we should be able to get a "spider view" with incoming and outgoing traffic.

There should be a way to show (mask by default):
- internal traffic (ads_cluster, access_log_sink, kuma_envoy_admin)
- passthrough traffic (inbound_passthrough_ipv6, inbound_passthrough_ipv4, outbound_passthrough_ipv4, outbound_passthrough_ipv6)
- inactive clusters

We'd generate this using metrics + clusters
A very simplistic example:

<img width="1217" alt="image" src="https://github.com/kumahq/kuma-gui/assets/702355/5455a1ac-dd74-4c1a-a2a3-af0d22936859">

Stats would show in each of the "legs" making a difference between http and tcp. A click on one of the "legs" could open a tray with XDS/cluster/stats/policies just for this cluster.

Open questions:

1.  Do we need clusters?  (I think so because we may lazily compute metrics for inactive clusters).
2. Do we need the backend to expose metrics in a better format? (json, prometheus?)
3. Do we want to show downstream and upstream stats separately?
4. Stats are point in time aggregates since the DP start. We could show `static` (show aggregates) or `stream` (Poll every X seconds and do the diff) keep in mind we don't have a store like prometheus in this case. 
5. We should have a look at what happens when we have a HTTP route on top of this (Do we show extra stuff on a leg?).

xref:

- https://github.com/kumahq/kuma/issues/2363
- https://github.com/kumahq/kuma-gui/issues/910

**Comment by lahabana** [comment]
Some use-cases:

- I'm a user trying to figure how much traffic my pod received
- I'm a user and I notice errors I want to see if errors come from upstream services or directly from my app
- I know something is wrong I want to see if it's envoy or the upstream app
- I want to see if a policy had any effect on an outbound of a dataplane (see envoy config)

**Comment by johncowen** [comment]
I 'think' we can close this since the initial build is up, we can then create new issue for improvements as we go. 

I'll go ahead and close but feel free to re-open if still needed, relevant PRs:

- https://github.com/kumahq/kuma-gui/pull/1807
- https://github.com/kumahq/kuma-gui/pull/1839
- https://github.com/kumahq/kuma-gui/pull/1866
