### ISSUE TITLE
Switch our CLI tests to use vitest instead of jest

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1568]
### Description

The vast majority of our frontend/DOM code is now tested in a browser via Cypress.

We have comparatively little non-DOM code tested via the CLI using jest, I'd like to add more.

Before we do, we should take the opportunity to move to `vitest`

Why? (my opinions)

- We use `vite` for our builder, using `vitest` for our test runner probably means less config and less dependencies, and one less "type of environment".
- It's more modern (we've had issues with jest and more modern JS features)
- `vitest` Follows a very similar APIs to `jest` so I would guess its a very small amount of effort to do this.

**Comment by lahabana** [comment]
Jest is only in Kuma-gui and vitest is almost api compatible with jest so that should be a straightforward swap.
