### ISSUE TITLE
Add summary tray functionality to list views

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1570]
### Description

We designed trays "summary" and we now implement them. It's worth discussing what info we want in there (probably not everything is useful).

**Comment by kleinfreund** [comment]
As a preparation, I’ll add a feature to AppCollection that allows selecting a row so that consuming components can add custom logic to this interaction (it currently always goes to the detail view).

This is being done in https://github.com/kumahq/kuma-gui/pull/1601.
