### ISSUE TITLE
Filter on policies list

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-gui#1639]
### What happened?

Should be able to filter on various fields on each policy list display

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's do filtering by name for now. The backend already supports this.

**Comment by kleinfreund** [comment]
Note for later reference, I just tried a couple of APIs locally and the `name` prefix filter works for:

- /zones
- /zones/_overview
- /meshes
- /meshes/:mesh/dataplanes
- /meshes/:mesh/:policyTypePath

and doesn’t work for:

- /meshes/:mesh/service-insights

**Comment by lahabana** [comment]
Needs to be done after: https://github.com/kumahq/kuma/issues/8908

**Comment by johncowen** [comment]
Policy filtering was added in https://github.com/kumahq/kuma-gui/pull/2666

We should probably close this and make separate issues for any other areas where we want name based filtering.

---

Separately if we want to add something more than name based searching, we should again make a separate issue as I'm guessing that would need backend support?

**Comment by lahabana** [comment]
Superseeded by: https://github.com/kumahq/kuma-gui/issues/3134
