### ISSUE TITLE
Support zone mode

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1686]
### Description

With https://github.com/kumahq/kuma/issues/8190 we'll have the GUI in a zone. This means that the GUI should support this. There will likely be NO difference between standalone and zone GUI as zone is the future of Zone.

We may add a page to show KDS connection state of something like this.

**Comment by kleinfreund** [comment]
In https://github.com/kumahq/kuma-gui/pull/1875, I’m adding the `zone` entry to our translation files so that the UI at least renders in zone mode.

**Comment by lahabana** [comment]
There's an extra field called: `zone_instance_id` that can be present (it's new so it dpends). Probably worth showing

**Comment by kleinfreund** [comment]
Note: The "name" of the Zone in zone mode is in /config

Also, /config includes whether KDS is enabled. If it’s not enabled, there isn’t going to be a Zone Insight. If it’s enabled, it behaves like in global mode; however, the subscriptions data is different.

**Comment by kleinfreund** [comment]
xref: https://github.com/kumahq/kuma/issues/8767

**Comment by kleinfreund** [comment]
We changed our mind on this again and will do the following on the UI side:

- global mode: nothing changes
- zone mode + KDS enabled: nothing changes, the GUI will be disabled on the backend side
- zone mode + KDS disabled: make everything behave like standalone mode behaves currently (essentially, replace mentions of `standalone` with `zone`, i.e. deprecate standalone mode)
