### ISSUE TITLE
Clicking Exit in the CreateView takes me to a different View to which I came from

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1706]
### What happened?

When I click [Create Zone] from the home page, and then I click [Exit] I'm taken to the Zone listing page, not back to the page where I clicked the [Create Zone] button (home). The [Exit] button should take you back to the same page that I came from.

The same can happen in other areas of the GUI not just Zones.

**Comment by lahabana** [comment]
First ask Erick about general UX on these

**Comment by johncowen** [comment]
> DesignSync: These 'pages' are modals, so clicking the exit button should work as if you close the modal. i.e. take you back to the page from where you opened it (use javascript `back` functionality or similar)
