### ISSUE TITLE
Add possibility to copy service name from Dataplane proxy view 

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma-gui#1747]
### Description

It would be nice to be able to copy the service name from data plane view instead of going back to service

**Comment by jakubdyszkiewicz** [comment]
> Triage: also add this to service list view please 🙏

**Comment by kleinfreund** [comment]
These views have changed a bit in the meantime, so I’d like to ask for some more direct requirements here. Copying the service name from the service list view is straightforward. Does it also make sense to copy the individual services from the data plane list view?

And for the detail views, what’s missing there?

Dataplane list view

![image](https://github.com/kumahq/kuma-gui/assets/5774638/748481e5-e5c1-4eb2-b56e-3e2e2ca63f91)

Dataplane detail view (standard proxy)

![image](https://github.com/kumahq/kuma-gui/assets/5774638/fa4a697a-960c-4a3d-bb1f-ecc0cabd481b)

Dataplane detail view (built-in gateway)

![image](https://github.com/kumahq/kuma-gui/assets/5774638/2443b5e7-dfa5-4b1a-89e6-cfcaf464811e)

Service list view

![image](https://github.com/kumahq/kuma-gui/assets/5774638/f647ad96-049e-4ff7-8f7c-e030ccc76642)
