### ISSUE TITLE
Persist code block filter button state in the browser URL

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1752]
Similar to https://github.com/kumahq/kuma-gui/pull/1711, also persist the filter button on/off state in the browser URL so that it persists across browser refreshes

**Comment by lahabana** [comment]
Blocked until we land on kongponents alpha

**Comment by kleinfreund** [comment]
For reference, the Kongponents feature PR this depends on: https://github.com/Kong/kongponents/pull/1807
