### ISSUE TITLE
Upgrade Vite 4 to 5

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#1791]
Migration guide: https://vitejs.dev/guide/migration.html

**To do**:

- Update package @vitejs/plugin-vue
- Remove package vite-plugin-rewrite-all
- Update package vite-svg-loader
- Set package.json `type` field to `module`
- Change file extension of the following files to `.cjs` as they don’t support (or aren’t imported) as ES modules:
  - dev-utilities/deprecatedUtilityClasses.js
  - .eslintrc.js
  - stylelint.config.js
- Change module format of the following files to ESM:
  - docgen.config.js
- Change import `import createEsbuildPlugin from '@badeball/cypress-cucumber-preprocessor/esbuild'` to `import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild'`

**Blockers**:

- [vite-plugin-html](https://github.com/vbenjs/vite-plugin-html) using deprecated features:
  - `plugin 'vite:html' uses deprecated 'enforce' option. Use 'order' option instead.`
  - `plugin 'vite:html' uses deprecated 'transform' option. Use 'handler' option instead.`
  - **Possible strategy**: Use [Vite’s native environment variable replacing mechanism](https://vitejs.dev/guide/env-and-mode.html#html-env-replacement).
- [vite-plugin-html-env](https://github.com/lxs24sxl/vite-plugin-html-env) using deprecated features:
  - `plugin 'rollup-plugin-html-env' uses deprecated 'transform' option. Use 'handler' option instead.`
  - **Possible strategy**: Use [Vite’s native environment variable replacing mechanism](https://vitejs.dev/guide/env-and-mode.html#html-env-replacement).

**Comment by johncowen** [comment]
@kleinfreund could you let me know what this upgrade is giving us, apart from it being the newer major

**Comment by jakubdyszkiewicz** [comment]
Blocked on https://github.com/kumahq/kuma-gui/pull/1799#issuecomment-1849731563
"Let's reconsider merging this in January"
