### ISSUE TITLE
Kuma manager display issue on Safari

### ISSUE THREAD

**Issue by liyangau** [kumahq/kuma-gui#183]
## Issue statement

Display issue when access Kuma Manager on Safari.

For example, `Skip to Dashboard` button, we can't see the text and the button background colour makes the text hard to read (white text + light gray backgroud)
![image](https://user-images.githubusercontent.com/71299093/126951027-bca8adf3-ab53-416f-bc70-d0e8fd868050.png)

**Comment by tomaszwylezek** [comment]
Hi @liyangau 
Thanks for reporting this issue.
I already provided a solution for that in https://github.com/kumahq/kuma-gui/pull/184
I will keep you informed when it will be merged & backported.

**Comment by tomaszwylezek** [comment]
@liyangau
The solution was merged and backported, closing the issue.
