### ISSUE TITLE
Migrate to new _rules API

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1838]
### Description

For inspect policies. We should use the newer API that scales better and work in global.

We can also discuss design a little if we review this as some outputs are a bit better.

https://github.com/kumahq/kuma/blob/bf05cb9456e0456e70ed8769dc88c18ad75e903c/api/openapi/specs/api.yaml#L20-L47

**Comment by kleinfreund** [comment]
Some more notes on this:

- Show the policy entries above the "Rules" heading **only in non-global mode**. They already don’t make sense in global mode and are being phased out. But for standalone/zone mode, they still are of some value.
- Replace the rule entries below the "Rules" heading with new content based on the new _rules API:
  - Group rules in three subsections: Proxy rules, To rules, and From rules
  - Group from rules by their inbound first and then by policy type (as we do for the current rule entries)
  - Group proxy rules and to rules by policy type
  - Matchers behavior:
    - Empty array means everything
    - Matchers are always and-chained (i.e. `&&`)
    - The representation for a couple of matchers should use the form `!kuma.io/service:foo && !kuma.io/service:bar && kuma.io/service:baz`
