### ISSUE TITLE
Links in first table column don’t get underlined on hover

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#1882]
### What happened?

The links in the first column of our tables don’t get underlined on hover. Generally, links in our application do that.

I think that’s a bug and should be fixed.

**Comment by jakubdyszkiewicz** [comment]
> Triage: check what is behavior in mink

**Comment by kleinfreund** [comment]
This doesn’t really have an analogy in Konnect as tables there typically don’t have links in their name columns.
