### ISSUE TITLE
Use policy summary tray for origin policies in Dataplane policies tab

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#1916]
### Description

For each origin in an entry shown in the Dataplane policies tab, we want to show a summary tray instead of going to the policy detail view directly.

**Comment by johncowen** [comment]
The below screengrabs show the link that current takes you to the policy detail page, and also what the summary panel should look like (it should look that same as how it currently looks on the policy listing page)

### Origin Policy Link

<img width="1717" alt="Screenshot 2024-05-17 at 15 11 29" src="https://github.com/kumahq/kuma-gui/assets/554604/417252c9-78a3-476f-a5ab-af733597a3b0">

### Policy Summary Panel in the Policies listing page

<img width="1722" alt="Screenshot 2024-05-17 at 15 23 17" src="https://github.com/kumahq/kuma-gui/assets/554604/c3414b59-661b-4a4d-9457-1330e94c0d61">

**Comment by schogges** [comment]
@kleinfreund @johncowen I just wanted to let you know that I have started to work on this 😃
