### ISSUE TITLE
Implement tray for DPP outbounds

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1960]
### Description

Let's discuss here further details

**Comment by johncowen** [comment]
See:

- https://github.com/kumahq/kuma-gui/pull/1997
- https://github.com/kumahq/kuma-gui/pull/2015
- https://github.com/kumahq/kuma-gui/pull/2041

**Comment by johncowen** [comment]
The above 3 PRs are merged, there will be follow up work, but that will be cleanup and any refactoring of things I noticed while I was in "feature mode".

Closing this
