### ISSUE TITLE
Gateway view

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1994]
### Description

Currently gateways are not very liked.

MeshGateway are shown in policies when they are not policies. Hard to make a difference between a provided gateway and a mesh gateway...

We should probably add a tab "Gateways" to:

<img width="847" alt="image" src="https://github.com/kumahq/kuma-gui/assets/702355/9024590d-a862-422e-a665-1d979af5722a">

In the case of a builtin gateway we'd be able to show the routes etc attached.

**Comment by lahabana** [comment]
This is a new tab: "Gateway" on /meshes/<meshName>/gateways

With 2 lists:
- builtin (sourced from: /meshes/<meshName>/meshgateways)
- delegated (sourced from serviceInsight)

**Comment by kleinfreund** [comment]
Design: https://www.figma.com/file/fsHrIqFubO5pVwQb6iH0z5/MINK-internal-%2F-external-services?type=design&node-id=7-6203&mode=design&t=hAOInXlxrLoNCwBu-0
