### ISSUE TITLE
policies for builtin gateway pod is broken

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#2034]
### What happened?

<img width="1661" alt="image" src="https://github.com/kumahq/kuma-gui/assets/702355/4ce0d02a-fd5f-4866-bf95-5b9bd717741b">

This should be the same as regular dataplanes now

**Comment by kleinfreund** [comment]
@lahabana Has the behavior of the `/meshes/:mesh/dataplanes/:dataplane/policies` API for built-in gateways changed then to make it be compatible with the view used for standard proxies and delegated gateways?

Specifically, doesn’t the `/meshes/:mesh/dataplanes/:dataplane/policies` API for built-in gateways produce a `MeshGatewayDataplane` object rather than a `SidecarDataplane` object?

**Comment by lahabana** [comment]
The /policies is getting removed. It should be the `_rules` API which works well enough for gateway DPP. There's done the road an API to get the matches for a MeshGateway: https://github.com/kumahq/kuma/blob/df79d3a77cae0d72fddd4a7bc87857ab4db8c486/api/openapi/specs/api.yaml#L33-L67

but that will be used in: https://github.com/kumahq/kuma-gui/issues/1994

**Comment by kleinfreund** [comment]
I think I understand. Though one special case for built-in gateways should be that they can _never_ show the legacy policies section we currently show in non-global mode (as the API that is based on doesn’t result in a SidecarDataplane). Is that correct?

**Comment by lahabana** [comment]
But this difference doesn't exist with the `_rules` api.
For regular DPPs we never use the legacy policies api anymore no?

**Comment by lahabana** [comment]
Wait the `/policies` endpoint hasn't changed. So if we keep it around for zones we should keep it. In pseudo code:

```
showRulesAPIResult()
if !global {
   whateverWeWereDoingBeforeThisAPI() // There's a different case for MeshGateway dpp and the rest and this should be kept
}
```

**Comment by kleinfreund** [comment]
By `whateverWeWereDoingBeforeThisAPI()`, do you mean "keep the current behavior for built-in gateways which is show routes and listeners based on the response of /policies and don’t use the /_rules-based view"?

**Comment by kleinfreund** [comment]
So, to summarize, we have the following matrix for when to show what. Legacy policies refers to UI based on /policies (which are different depending on Dataplane type). Rules-based policies refers to UI based on /_rules.

| Dataplane type    | Mode   | Legacy policies | Rules-based policies |
| ----------------- | ------ |:---------------:|:--------------------:|
| Standard proxy    | zone   | ✅ (based on SidecarDataplane) | ✅ |
| Delegated gateway | zone   | ✅ (based on SidecarDataplane) | ✅ |
| Built-in gateway  | zone   | ✅ (based on MeshGatewayDataplane) | ✅ |
| Standard proxy    | global | ❌ | ✅ |
| Delegated gateway | global | ❌ | ✅ |
| Built-in gateway  | global | ❌ | ✅ |

**Comment by lahabana** [comment]
That's right
