### ISSUE TITLE
Check for kuma.io/display-name when displaying names

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2051]
### Description

We should do this in our data layer.

Check for a `kuma.io/display-name` and use that instead of the name if its present

At least 2 options:

1. We should also move/duplicate the actual `name:` to something else (like `id:`) for if we need it for other things .If `kuma.io/display-name` doesn't exist, `name:` stays as it is, and we just copy the same value to `id:`.
2. Keep `name:` as it is but create a new field called `label` or `displayName`, then change where we use `name` in the View to use `theNewFieldName:` instead. If `kuma.io/display-name` is not set we just copy the `name:` to the new field.
3. ....

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's also display kube namespace if we do this. On Kubernetes, the display name is a policy name without a namespace
