### ISSUE TITLE
Tweak Dataplane view display of passthrough and inactive traffic

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#2087]
### Description

Think about the case where you are at the “end service” e.g. Redis which had no outbound traffic, options (we preferred option 1 here):

- Don’t show passthrough at all. Show a completely different “empty state” which says you have no outbound traffic, but <this-many> outbounds.
- Reverse the inactive toggle (good because you see any outbounds, bad because you see all the zero traffic outbounds.)

Consider putting the number of zero traffic outbounds next to the Inactive toggle

**Comment by lahabana** [comment]
This seems to be the best behaviour we can do at least for now. Closing this as rotten
