### ISSUE TITLE
Add matching policies in tray of dataplane view

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#2124]
### Description

This is super useful to actually understand what config you have on an inbound or an outbound

**Comment by johncowen** [comment]
PRs addressing this:

- https://github.com/kumahq/kuma-gui/pull/2277
- https://github.com/kumahq/kuma-gui/pull/2289

Those are just for inbounds on sidecars, so we might want to split this issue up into further issues, instead of of a longer running umbrella issue.

**Comment by johncowen** [comment]
Closed by https://github.com/kumahq/kuma-gui/pull/2315

There are more PRs to come here that do more minor things such as group the rules by policy type (https://github.com/kumahq/kuma-gui/pull/2322) plus some more design related PRs, but the top-level task here is complete.
