### ISSUE TITLE
Move creation/modify date inside the "top card"

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#2161]
### Description

This would make things a little easier to read:

<img width="1462" alt="image" src="https://github.com/kumahq/kuma-gui/assets/702355/8dfaa6f7-7269-4e41-a1bd-08576668e8c7">

**Comment by jakubdyszkiewicz** [comment]
> Triage: the screenshot is an example of a view in Konnect. This is what we want

**Comment by johncowen** [comment]
Done as part of https://github.com/kumahq/kuma-gui/pull/2677
