### ISSUE TITLE
Improve zone inspect view

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#2164]
### Description

1. Since 2.6.0 there's a `zoneInstanceId` field which is more useful to users that the `globalInstanceId`. 

See:

```json
 "zoneInsight": {
  "subscriptions": [
   {
    "id": "792e2051-4f0c-4df6-ab03-1701b2b8af99",
    "globalInstanceId": "mink-control-plane-5c98999c7c-wsc2t-875e",
    "connectTime": "2024-02-06T12:38:04.230480952Z",
    "disconnectTime": "2024-02-06T16:14:13.958395810Z",
    "status": {
     "lastUpdateTime": "2024-02-06T15:14:54.374063306Z",
     "total": {
      "responsesSent": "45",
      "responsesAcknowledged": "45"
     }
    },
    "version": {
     "kumaCp": {
      "version": "2.6.0",
      "gitTag": "2.6.0",
      "gitCommit": "53744108710a5151b4b8121f7b9392ffc0f3651c",
      "buildDate": "2024-02-01T13:41:52Z",
      "kumaCpGlobalCompatible": true
     }
    },
    "generation": 86,
    "authTokenProvided": true,
    "zoneInstanceId": "kong-mesh-control-plane-84ccc98fc4-6zzzv-feca"
   },...
```
We should show this instead of the Global InstanceId as this is more useful
<img width="1464" alt="image" src="https://github.com/kumahq/kuma-gui/assets/702355/97aff79c-49f7-4594-ad9a-821b24eaff3d">

2. We should also show: the version at the top. Finally each subscription should have a `copy raw` button to just get the json/yaml of the subscription. We should also show if the version is not the latest to suggest upgrade to customers.
3. We should make it obvious when the zone is returning NACKs (I think we may need a backend change to be able to do this).

**Comment by johncowen** [comment]
- ZoneInstanceID and Version in the accordion title: https://github.com/kumahq/kuma-gui/pull/2586

Still to do:

- Finally each subscription should have a copy raw button to just get the json/yaml of the subscription.
- We should also show if the version is not the latest to suggest upgrade to customers.
- We should make it obvious when the zone is returning NACKs (I think we may need a backend change to be able to do this).

**Comment by lahabana** [comment]
Let's also put the last connected subscription's version in the top bar and then do change the colour if it doesn't match the global cp version (with a tooltip to indicate version is different). If very is not an exact semver (.e.g: 0.0.0-preview.vdeadbeef) don't change the colour (I think it's more or less if not match `[0-9]+\.[0-9]+\.[0-9]+`).

**Comment by johncowen** [comment]
I've made 2 new issues to cover the things we decided to do that was left over here, and then this issue will be closed by https://github.com/kumahq/kuma-gui/pull/2621
