### ISSUE TITLE
Apply styles and custom logic only to specifically marked "name" columns in AppCollection

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#2293]
### Description

We have some code that relies on the first column of an AppCollection to be the "name" column. This isn’t always true and causes a bunch of weird logic and styles that aren’t robust at all:

Instead, we should specifically mark the name columns with a selector on only apply custom styles and custom logic if this selector is found in a table row.

Problematic examples:

https://github.com/kumahq/kuma-gui/blob/878e471739bc71fce5fd60cafdbe8170c71f2b39/src/app/application/components/app-collection/AppCollection.vue#L215-L223

https://github.com/kumahq/kuma-gui/blob/878e471739bc71fce5fd60cafdbe8170c71f2b39/src/app/application/components/app-collection/AppCollection.vue#L227-L239

https://github.com/kumahq/kuma-gui/pull/2292/files

**Comment by johncowen** [comment]
Note: This is kind of a dupe of https://github.com/kumahq/kuma-gui/issues/2275

**Comment by kleinfreund** [comment]
I’m closing this as a duplicate of https://github.com/kumahq/kuma-gui/issues/2275 (which still needs addressing as we have several `td:first-child` selectors in AppCollection)
