### ISSUE TITLE
Hide Legacy policies when there are none instead of showing an empty state

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#2302]
### Description

See title

**Comment by johncowen** [comment]
Also see https://github.com/kumahq/kuma-gui/pull/2269

> Theres a question about whether we should show the "Legacy Policies" block at all if its empty, but seeing as we do for gateway dataplanes I decided at least for the moment to continue to show it.

But we decided that because they are 'legacy' we shouldn't show this block afterall.
