### ISSUE TITLE
Consider using display-name for Mesh listings

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2389]
### Description

Mesh API response seem to have a `kuma.io/display-name` but no `k8s.kuma.io/namespace`.

Is this correct functionality? If not we should make an additional kuma repo issue. Either way, we should probably still use the `display-name` for Meshes? Although not entirely sure if this can currently be different from the `.name`

Guessing this isn't super necessary for 2.7, but I could be wrong. I added a 2.7 milestone incase, but please change if its not necessary for 2.7

**Comment by jakubdyszkiewicz** [comment]
> Triage: Mesh is not namespaced scope. Mesh name is always equal to display name
