### ISSUE TITLE
Disable Datadog Logs and Event collection

### ISSUE THREAD

**Issue by austince** [kumahq/kuma-gui#240]
In line with the CNCF guidelines found in https://github.com/kumahq/kuma/issues/3050, we should disable these collections since 1) they are published to Kong's DataDog account and 2) it is not opt-in unless I've missed something about how the initialization works.

 cc @jpeach

**Comment by jpeach** [comment]
@Bradamant3 @subnetmarco

**Comment by tomaszwylezek** [comment]
It will be disabled by default in Kuma 1.4
