### ISSUE TITLE
MeshService list and view

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#2469]
### Description

MeshService has landed and we should make it appear in the list and have a detail view.

What apis on the backend are we missing (policy attachment probably missing for .e.g).

Will need a feature flag (or maybe we just don't show if there's no MeshService in the meshinsight?)

**Comment by johncowen** [comment]
Related PRs:

- https://github.com/kumahq/kuma-gui/pull/2546
- https://github.com/kumahq/kuma-gui/pull/2561
- https://github.com/kumahq/kuma-gui/pull/2562
- https://github.com/kumahq/kuma-gui/pull/2564

**Comment by johncowen** [comment]
Closing this seeing as list and details views where done in the above PRs. Theres also #2470 to cover MeshService deeper integration
