### ISSUE TITLE
MeshService deeper integration

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#2470]
### Description

Policy attachment/inspect api should be usable from the GUI.

MeshGlobalService (or whatever this related to). MeshHostnameGenerator and other things like this.

TODO complete this issue with precise things to integrate with @jakubdyszkiewicz and @michaelbeaumont

**Comment by jakubdyszkiewicz** [comment]
> Triage: another option is to just not show HostnameGenerator at all

**Comment by johncowen** [comment]
Not super clear what (if anything) is to be done here at this point in time.

https://github.com/kumahq/kuma-gui/issues/2469 is covering basic list/summary/detail and covers this part of @michaelbeaumont s comment above:

> Service view - select services by type
> Dropdown selector for service type
> OR button per service type

(we went for button per service type)

I think 

- Policy attachment/inspect api should be usable from the GUI.
- MeshHostnameGenerator and other things like this.

Are still work in progress from the backends perspective, and could be better to close this issue and create two new ones for these two points once its clear what's to be done.

**Comment by johncowen** [comment]
I'm going to take this one out of 2.9. 

Theres an issue to cover:

> Policy attachment/inspect api should be usable from the GUI.

for 2.9 (https://github.com/kumahq/kuma-gui/issues/2880)

And I don't believe we are aiming for GUI support HostnameGenerator for 2.9.

But let me know if this still needs to be in 2.9, we can add back the milestone
