### ISSUE TITLE
"Copy as K8s" no longer works

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2513]
### What happened?

If you load a fresh page with a "Copy as K8s" button on it and then click the "Copy as K8s" button, nothing is copied into your clipboard (whatever was there beforehand remains).

This seems to be only on `master` not on `release-2.7` so I would imagine its as a result of https://github.com/kumahq/kuma-gui/pull/2374 and/or related Kongponents upgrades

**Comment by kleinfreund** [comment]
Hm, I just tried it locally and it worked for me. This could be a browser-specific thing?

**Comment by johncowen** [comment]
Maybe, I just tried it again, and unless I'm missing something/doing something wrong it's not working here

**Comment by kleinfreund** [comment]
Hm, strange. I can somehow _sometimes_ reproduce it but not always?

**Comment by johncowen** [comment]
Definitely something up here, we've both reproduced it and looks like there is something weird going on when we look deeper.

**Comment by johncowen** [comment]
This still seems really broken, reopening.

Its also really confusing because since https://github.com/kumahq/kuma-gui/pull/2374 the `as K8s` button is actually a smaller button inside a button, so depending on where you click on the thing you can click one button or another.
