### ISSUE TITLE
subscriptions: Use table/panel GUI instead of accordion panes

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2623]
### Description

Taken from https://github.com/kumahq/kuma-gui/issues/2164

> Finally each subscription should have a copy raw button to just get the json/yaml of the subscription.

We should switch from using accordion panes for subscriptions to using a table/summary panel layout like the rest of the GUI.

In the summary panel we can have 2 tabs, [Overview] and [YAML]. Overview shows the information that is currently showing in the accordion panes, and the YAML tab can contain the YAML for the subscription (along with copy buttons etc)

**Comment by johncowen** [comment]
See https://github.com/kumahq/kuma-gui/pull/2664 for part of this

**Comment by lahabana** [comment]
xref for 2 other implems:

https://github.com/kumahq/kuma-gui/issues/2920
https://github.com/kumahq/kuma-gui/issues/2921
