### ISSUE TITLE
tables: Remove "Go to details" links

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2668]
### Description

- Remove "Go to details" links
- Replace with kebab/meatball menu, contain "View details" plus any other actions we might need.
- Remove any copy buttons after the "name of the thing" there are occasions where its not even copying the full text string that you probably want.
- Add clickable icon to the right of the name to also take you to the detail page.
- Potentially add a tooltip to the new icon saying that it is "View details"

---

Deciding factors/constraints:

1. Users should be able to choose whether to single click to see either a summary drawer or a detail page.
2. We want to consistently use a meatball/kebab menu on all our tables across all our applications (some have multiple actions)
3. We don't want any additional buttons/icons/links to clash with existing icons we have on to the left of the "name of the thing"

Some screengrabs of current table rows which we'd like to make more useful and consistent.

### Right hand copy button

![Screenshot 2024-06-20 at 16 42 33](https://github.com/kumahq/kuma-gui/assets/554604/a0114fbe-40a2-47ff-90e0-93242ebbdcfa)

### Both "Click details" and meatball menu

![Screenshot 2024-06-20 at 16 43 04](https://github.com/kumahq/kuma-gui/assets/554604/36001aa8-13f1-46a9-b087-f792419cb717)

### Left hand icon

![Screenshot 2024-06-20 at 16 43 34](https://github.com/kumahq/kuma-gui/assets/554604/94d3bca3-0ba3-4715-b23c-f405fb5bd815)

**Comment by johncowen** [comment]
I'm moving this to pending so it comes up in triage:

> Remove "Go to details" links - **Done**
> Replace with kebab/meatball menu, contain "View details" plus any other actions we might need.- **Done**
> Remove any copy buttons after the "name of the thing" there are occasions where its not even copying the full text string that you probably want.- ** Not Done**
> Add clickable icon to the right of the name to also take you to the detail page.- ** Not Done**
> Potentially add a tooltip to the new icon saying that it is "View details"- ** Not Done**

I want to make sure that we definitely want to do the things marked ** Not Done** for 2.9

**Comment by michaelbeaumont** [comment]
> Let's leave this as is for 2.9

**Comment by lahabana** [comment]
Ok let's keep it as is for the moment. If we dig deeper we should look at using the drawer for everything and parting with the "details" pages
