### ISSUE TITLE
Use grouped buttons for filtering by dataplane type

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2703]
### Description

Whilst I've made an issue here, theres something I'm not totally sure about, so would be good to chat through.

The change is the following:

![Screenshot 2024-06-28 at 11 39 42](https://github.com/kumahq/kuma-gui/assets/554604/dc29e2d0-2275-49bb-b53c-ceaaf55b446c)

![Screenshot 2024-06-28 at 11 40 54](https://github.com/kumahq/kuma-gui/assets/554604/52f45a4b-9772-4d3c-9ac2-66461605536c)

**Comment by Automaat** [comment]
design is reviewing this, lets not do it yet
