### ISSUE TITLE
Add YAML to summary drawers everywhere

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2922]
### Description

IMO lists of things in GUIs should be either:

1. A way to get somewhere
2. A way to compare things

NOT: A way to show "all-the-informations".

Point 2 above, along with our summary drawers make it easier to compare things such as YAML config. Not necessarily "at a single glance" as we can't display the YAML in every single row. But by single clicking we can show the YAML in each summary drawer for the row that you click on making it easy to click on several rows after each other to compare YAMLs.

This make it really easy to compare resources without having to navigate backwards and forwards between different pages and tabs.

We already have several places where we show the YAML in the summary drawer, sometimes in a "sticky tab" in a drawer, sometimes in a drawer with a `[Structured]/[YAML]` dropdown, and sometimes just the YAML on its own.

I think in a lot of places we can add the YAML on its own, for the summaries that are already quite busy we can decide how to add the YAML on a case by case basis. We may later decide for the sake of consistency to choose one approach whether we have a busy summary or not.

**Comment by johncowen** [comment]
Wanted to note that there are at least 2 places where we might _not_ want to show a yaml or drawer at all:

1. Legacy kuma.io services (aka internal services). Reason: These don't have a config to show, so we can't show any YAML. The listing is generally "A way to get somewhere", and that somewhere is generally the list of dataplanes for the service.
2. Meshes. This is a bit more tricky as Meshes _do_ have a YAML config, but! We added the mesh listing page as a replacement for the Mesh selector that we used to have in the left hand main nav (it was a native select menu, which when selected would take you straight to that mesh) i.e. this listing is primarily "A way to get somewhere".

Wanted to leave that info here. I suppose we could still show drawers for both, and in the case of Meshes the YAML also, but we should be intentional about doing _or_ not doing that taking the above points into account.

I don't think there are any other resources that have these question marks over them, for example I know that Dataplane and Gateways do not have a drawer with their YAML in them.

Hope this helps, please shout if the above isn't clear or if anyone had more to add/discuss.

**Comment by lahabana** [comment]
One thing is missing.

In https://deploy-preview-3262--kuma-gui.netlify.app/gui/meshes/default/data-planes/feed-proxy-8/summary-overview

- For dataplane overview remove inbounds parsed list and inline yaml (don't have tabs)
- For subscription use the Konnect structured/json view  (see RBAC in KM)

**Comment by johncowen** [comment]
Lets make a new issue for this:

> As of next I'd like to discuss if we really want to add the Structured/YAML dropdown to subscription. This introduces a whole new way of how we represent data. Instead it would probably make more sense to fully focus on the YAML representation and remove any duplicate information, that the user could also retrieve from the config itself.

And then when we've done the remaining YAML we can close this issue 🎉 but leave that new one for any discussion and tracking around "Consider adding structured/yaml dropdown"

**Comment by schogges** [comment]
> In order to show configs in summary drawers everywhere, we should add a summary drawer including the config for Gateways (both builtin and delegated).

I was investigating the resources and I think there is no config for the `delegated` gateway that we can show in the summary drawer. The configuration for a `delegated` gateway is part of other resources like `Dataplane`.
