### ISSUE TITLE
Add separate explanatory sentences for Service types views

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2928]
### Description

The sentences should go underneath the right hand side subnav, and we should have a separate sentence for each of Internal, External, MeshService, MeshMultiZoneService, MeshExternalService

**Comment by schogges** [comment]
@johncowen 
I think that I found the place for the descriptions/sentences. Please verify my assumptions and if possible provide me with or point me to the resources I need to fill in the sentences 🙂 

<img width="1222" alt="Screenshot 2024-10-25 at 11 17 40" src="https://github.com/user-attachments/assets/075b063d-840c-4a70-a48a-361fe8b7b9ea">

**Comment by johncowen** [comment]
Yeah thats it 👍 . I'd just left align them though. So literally move the existing one down underneath the buttons, same width/alignment.

**Comment by michaelbeaumont** [comment]
Not sure how long they should be but

> Internal: defined by `kuma.io/service` tags
> External: defined by `ExternalServices`
> MeshService: defined by `MeshServices`
> MeshMultiZoneService: defined by `MeshMultiZoneServices`
> MeshExternalService: defined by `MeshExternalServices`

Maybe we should link to the docs for the last 3? If we have space we could try to "define" them? Like "destinations in a single zone" and "multi-zone load-balanced destinations" and "explicit destinations outside of the mesh" or something
