### ISSUE TITLE
Introduce HostnameGenerators

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2956]
### Description

Build out initial views for HostnameGenerators. This should be built as a new 'module'. Installation of this new module should be done inside the existing `service-mesh` module, seeing as its a fundamental/essential part of our service-mesh software.

Views/frontend needed:

- [ ] A way to get there (possibly some sort of view or widget on the home page)
- [ ] ListView
- [ ] SummaryView
- [ ] DetailView

HTTP client types and data types already exist our OpenAPI generated typescript, so data interactions (`sources.ts` should be able to entirely use a OpenAPI generated HTTP client.

Patterns should probably follow one of the new service types i.e. MeshExternalService (a.k.a. if there's copy/pasta to be done MeshExternalService would be a good starting point)

Importantly, HostnameGenerators are a "top-level" construct similar to Meshes and Zones i.e. they don't have a parent. Despite this we don't want to put them in the main side menu just yet (or maybe never). Users will mostly just use the default HostnameGenerators and therefore barely need to know that they exist/are a thing. But for "power users" we still need a way for them to get to them and view them. Therefore we'd like to put a link and or view somewhere on the "home"/"control plane view" page so users can get to a HostnameGenerator listing page. This way they are as visible/accessible as the main side menu items, but are still visible/accessible when/if you need to get to them.

Contents of the detail and summary pages will be dictated by the contents of the HTTP API responses. The important thing will be to get the data on the page following existing patterns and we can then tweak and refine what's best to show and where to show it with the rest of the team.

**Comment by schogges** [comment]
I'd like to work on this 🙂 could you assign me please?
