### ISSUE TITLE
Add a warning for MeshExternalServices when `mesh` requirements are not met

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-gui#2957]
### Description

MeshExternalService requires:
- egress deployed (which requires mTLS and MeshTrafficPermissions)
- `routing.zoneEgress: true` (see bottom of https://kuma.io/docs/2.8.x/production/cp-deployment/zoneegress/#zone-egress)

would be nice to display a warning somewhere in `MeshExternalServices` tab if these requirements are not met

![image](https://github.com/user-attachments/assets/6d26dd07-851e-4525-a424-94eec10129b8)

so something like this maybe could work:

![image](https://github.com/user-attachments/assets/320ef02a-ea45-4ddb-8da5-cc7c776d64fc)

On the user side when they are not met the MeshExternalService won't work and will error out with:

```
/app # wget -O- http://mes-https.extsvc.mesh.local/
Connecting to mes-https.extsvc.mesh.local ([::ffff:242.0.0.1]:80)
wget: error getting response: Connection reset by peer
```

Which is not very helpful, not sure we can do something there 🤔

**Comment by jakubdyszkiewicz** [comment]
It does not required `routing.zoneEgress: true` now. However, it requires mTLS
