### ISSUE TITLE
Content aware viewer for Yaml and JSON

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#301]
### Description

We have many places that display yaml or json it would be good to have a container for these that enable easy collapsing some nested elements or doing search in the content.

Something similar to what a code editor would do with these formats.

**Comment by lahabana** [comment]
This must also include a copy button

**Comment by kleinfreund** [comment]
@lahabana Would you agree that the ability to search (in order to highlight matching lines) and filter (to only show matching lines grep-style) addresses this feature request?

**Comment by lahabana** [comment]
If it's json could we add collapsing as a feature too?

**Comment by kleinfreund** [comment]
It’s possible, but it would be quite some effort. While it’s somewhat simpler for JSON where we have a good representation for the syntax in form of the underlying JavaScript object (i.e. a collapsible section is determined from object and array values in the object), it’s not trivial either. As for filtering, this would be especially hard if we want to keep syntax highlighting for a JSON tree with collapsed regions.

I’d like to first see whether searching and filtering would make this feature obsolete.

**Comment by lahabana** [comment]
Ok then so let's consider that what you've done is fully covered here.

**Comment by lahabana** [comment]
This was done as explained previously by @kleinfreund
