### ISSUE TITLE
Rename backend to storageType

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#306]
### What happened?

We've agreed on renaming this it's at least present in the cp list

**Comment by kleinfreund** [comment]
The term backend is directly (i.e. not as part of content coming from the API) in two places in the UI.

* The Mesh wizard has a "Backend name:" field when setting up Logging, Tracing, and Metrics. Those values are then shown in the YAML content in the install step.
* The Zones CP overview has a table header "Backend". This corresponds to the `/config` API response’s `store.type` value.

I assume only the latter should be renamed. Is that correct?

**Comment by lahabana** [comment]
This is correct
