### ISSUE TITLE
Dot instead of underscores for Internal Services hostnames 

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-gui#3098]
### Description

The problem is if you want to use feature of DNS hostname with dots instead of `_` you need to replace it by hand. There should be a way for user to copy from the GUI hostnames with dots.

This is only for internal service tag services, not for mesh services

xref https://github.com/kumahq/kuma/issues/11869

**Comment by johncowen** [comment]
hey @jakubdyszkiewicz , I think I might have missed triage for this, so its not super clear to me what the ask is here.

Here's some grabs of the Internal Services listing and detail pages:

![Screenshot 2024-11-01 at 10 19 44](https://github.com/user-attachments/assets/944ffd3d-a478-4c4a-9eac-b23c49c7ba0f)

![Screenshot 2024-11-01 at 10 20 10](https://github.com/user-attachments/assets/c4f65173-8805-49a0-baef-6f0f1ebeb92b)

---

Erm, some things that might help me understand:

What's a hostname, the `addressPort`? I can't see any other fields in the API responses that "hostname" could refer to.
Currently the `addressPort` is visible in both the listing and detail pages (we call it just `Address`), so you can either copy it by selecting the text as you normally would, or you can use the provided copy button also. The `addressPort` property already contains both underscores and dots.

I'm guessing there's something I'm completely missing here, maybe there is some other way of configuring an internal service that gives me a hostname property?

Anyway, lemme know!
