### ISSUE TITLE
Add link to `HostnameGenerator` list view to home

### ISSUE THREAD

**Issue by schogges** [kumahq/kuma-gui#3174]
### Description

This is a follow-up to #2956.

We need to find a good spot to put the link for the `HostnameGenerator` list view on the home view or into the side-/topbar.
`HostnameGenerator`s are not specific to a `mesh` or a `zone` and are a top level resource. They are not as important as `mesh` and `zone` resources and therefore should not be on the same level of navigation options. We expect that only a few users will check the views.

**Comment by lahabana** [comment]
Let's add this to the actions button in the home page. This button is currently only present on MinK it should now always be here with extra options on Mink.
