### ISSUE TITLE
Unsupported version of Kuma DP (1.6.0)

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-gui#321]
### What happened?

![image](https://user-images.githubusercontent.com/5459824/164194611-19c5fa32-f8c9-4cf6-99b3-24cfd02d9fa1.png)

**Comment by lahabana** [comment]
Will this get fixed by: https://github.com/kumahq/kuma/issues/4203 ?

**Comment by parkanzky** [comment]
> Will this get fixed by: [kumahq/kuma#4203](https://github.com/kumahq/kuma/issues/4203) ?

Yes.

**Comment by lahabana** [comment]
From triage it sounded we'd still need a fix for older version as we wouldn't #4203 wdyt?
