### ISSUE TITLE
The counters in the sidebar are not refreshed when the table refresh button is pressed

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma-gui#327]
### What happened?

In the picture below, 6 standard DDPs are seen in the table, but the counter next to "Standard" in the side bar still shows "3" instead of "6".

<img width="1726" alt="Screen Shot 2022-05-18 at 3 34 13 PM" src="https://user-images.githubusercontent.com/964813/169166561-17118446-cb3c-4f2b-a836-688867a01997.png">

**Comment by lahabana** [comment]
Triage: The sidebar of the UI is updated at a poll interval. We don't have a good scalable way to propagate events down to the GUI. One way would be ws but that might not be something we want to add to the CP just for counters in the sidebar.

Maybe an alternative is showing that this is polled. Maybe removing the counters would just be simpler.

**Comment by subnetmarco** [comment]
What is the interval duration today?
