### ISSUE TITLE
Policy wizard in the GUI

### ISSUE THREAD

**Issue by brentos** [kumahq/kuma-gui#331]
### Description

Currently the Kuma GUI will show all of the policies that are configured and you can view the YAML for them. It would be great if you could click a "new" button and it would generate an example of the policy that could be edited or copied. Right now you need to navigate to the docs and copy/paste from there. Even better would be to have a form where you could enter all of the parameters for the config and generate the exact YAML needed.

**Comment by kleinfreund** [comment]
This is still missing and we haven’t planned working on it so far.

**Comment by lahabana** [comment]
Just thinking about this out loud. Policies have schema.yaml now. 
Are there tools to create forms out of json schemas?
If yes we could consider exposing the schema from the cp and leverage this to create wizards no?

**Comment by jakubdyszkiewicz** [comment]
Do we still want to do this?

**Comment by michaelbeaumont** [comment]
Let's close it for now and if we need this we'll create this again
