### ISSUE TITLE
Policy UI should be dynamically generated from registered endpoint

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#336]
### Description

To avoid a lot of code repetition we're adding a `/policies` endpoint. All policies component should be extract from this component (including the sidebar). This should remove a lot of boilerplate code and not require any work when we add a new policy.

Ideally there should be a way to add extra policy specific feature.

**Comment by kleinfreund** [comment]
Closing in favor of https://github.com/kumahq/kuma-gui/pull/344.
