### ISSUE TITLE
Search capability on dataplane list

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-gui#337]
### Description

We should add the capability to search within the UI. Maybe a general search box, or one that supports a syntax, e.g. `dpp:<search_term>` or `zone:<search_term>`. Should it fuzzy match? Etc etc...

**Comment by lahabana** [comment]
xref #382

**Comment by lahabana** [comment]
There's a `name=` parameter to dataplane+insights endpoint

**Comment by kleinfreund** [comment]
This was added as part of https://github.com/kumahq/kuma-gui/pull/505.
