### ISSUE TITLE
Dependabot seems to be unable to create PRs for vulnerable dependencies

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-gui#339]
Issue edited

Mirror issue: https://github.com/kumahq/kuma-website/issues/939

### What happened?

Our GH dependabot seem to be unable to open PRs to fix vulnerable dependencies: 
https://github.com/kumahq/kuma-gui/security/dependabot

This might be due to dependencies having [exact version](https://github.com/kumahq/kuma-gui/security/dependabot/14) requirement.

Need to investigate and fix this.

--- 

~~Our GH security advisories / dependabot updates seem to be not working.~~

~~When going to https://github.com/kumahq/kuma-gui/security/advisories we don't see any security advisories listed, but running `yarn audit` shows vulnerabilities:~~

```bash
yarn audit

...
165 vulnerabilities found - Packages audited: 2322
Severity: 2 Low | 67 Moderate | 76 High | 20 Critical
```

~~We need to fix this and have an automatic update mechanism just like in Kuma.~~

**Comment by michaelbeaumont** [comment]
@slonka aren't they all listed in https://github.com/kumahq/kuma-gui/security/dependabot?

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's first try to merge https://github.com/kumahq/kuma-gui/pull/302 and let see if dependabot creates more PR

**Comment by kleinfreund** [comment]
The PR https://github.com/kumahq/kuma-gui/pull/302 needs some manual action to actually do the update. For this, I created https://github.com/kumahq/kuma-gui/pull/343.

In doing so, I noticed that our CI runs Node.js 12 which is really quite old. It reached end-of-life support in April. We should update the CI to run Node.js 16.

**Comment by kleinfreund** [comment]
Closing this because I think this should work regularly now.
