### ISSUE TITLE
Links to kuma documentation 404 when using Kong Mesh 1.8.2

### ISSUE THREAD

**Issue by brentos** [kumahq/kuma-gui#360]
### What happened?

Kong Mesh 1.8.2 running in k8s/kind on my laptop in standalone mode

When I click the "Check your mesh!" button, all of the documentation links in the modal window give a 404 when clicked. For example, the Traffic Metrics link goes here: https://kuma.io/docs/1.8.2/policies/traffic-metrics/

The version seems to be incorrect since the Kuma version and Kong Mesh version are not the same.

Expectation: links go to the correct documentation pages and do not 404

**Comment by kleinfreund** [comment]
I’m pretty sure this issue was fixed in https://github.com/kumahq/kuma-gui/pull/340 which was merged a few days after 1.8.2 was released.

**Comment by lahabana** [comment]
Indeed

**Comment by kleinfreund** [comment]
To elaborate on this: going forward, the documentation URLs used in the Kong Mesh UI will be generated with version strings _of the underlying Kuma_. Previously, the UI just knew about one version: for Kuma GUI that’s the underlying Kuma version; for Kong Mesh GUI, that’s the underlying Kong Mesh version.
