### ISSUE TITLE
Bottom tab container in UI should always be displayed, data overview should be scrollable

### ISSUE THREAD

**Issue by brentos** [kumahq/kuma-gui#375]
### Description

The bottom tabbed container that shows the details of the selected row should always be displayed on the screen. For example, the Data Plane Proxies list can get very long, and the details of the selected DPP are displayed at the very bottom of the list, which then requires the user to scroll to the bottom of the page after selecting an item in the list and then scrolling back up to make a new selection. It would be more usable to have the details always displayed on screen (either at the top or bottom) and then the data table should have its own scroll bar so users can scroll through. It also might be nice to be able to navigate through the data table with up and down arrow to go to the previous / next entry.

**Comment by lahabana** [comment]
Will be done as part of: #382
