### ISSUE TITLE
Rewrite service view

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#383]
### Description

Let's rewrite the service view.

Some features:

- Possibility to drill-down from services down to dataplanes behind it and their corresponding details view
- Merging external and internal services into 1 view (it's just a type and a contextualized info)
- Filter by protocol type/zone...

**Comment by kleinfreund** [comment]
**Soft blocker**: This change should be serviced (!) with a new API endpoint for retrieving a paginated list of services (i.e. service insights *and* external services).

Keeping track of the two independent pagination states is a big hassle if we want to display services as one entity in the GUI. Displaying them in separate tables would still be easy, but that’s pretty much what we already got.

**Comment by kleinfreund** [comment]
**Resolution for https://github.com/kumahq/kuma-gui/issues/383#issuecomment-1257907957**: We will make changes to the `service-insights` endpoint.

- The endpoint will now also include external services. An external service insight on this endpoint has the fields `type`, `mesh`, `name`, `creationTime`, `modificationTime`, `serviceType: 'external'`, and `address`
- A `serviceType` field of type string with the possible values `'internal'` and `'external'` is added.
- For service insights, the field `address` is added and set to the .mesh address. This should also be added to the service insights endpoint that retrieve the actual entity.

(cc @jakubdyszkiewicz)
