### ISSUE TITLE
Multiple requests for ZoneOverview

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-gui#398]
### What happened?

![image](https://user-images.githubusercontent.com/5459824/194089950-c10f4d1b-4a23-4199-b5b4-fbe8abc7bf6f.png)

We should not have sequential requests for zone overviews, it significantly delays the data plane list.

Visible only in multizone.

**Comment by kleinfreund** [comment]
Cause: a version mismatch check for data planes with a zone tag makes an API call to retrieve version information from the `/zones+insights/:zone` endpoint:

https://github.com/kumahq/kuma-gui/blob/b315d5c5a9b528b205a3ad9dbb75da66c5d32d66/src/dataplane.ts#L169-L174
