### ISSUE TITLE
Kubernetes representation isn’t correct for new resources that already have spec field

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#423]
### What happened?

Kubernetes representation isn’t correct for new resources that already have spec field. *Then*, spec shouldn’t appear twice in the resulting YAML.

Needs backend work (https://github.com/kumahq/kuma/issues/6658) to tell GUI whether a resource uses new format.

**Comment by slonka** [comment]
@kleinfreund can you link to the backend issue for this?

**Comment by kleinfreund** [comment]
@slonka I don’t think there is a backend issue for this, yet.

**Comment by slonka** [comment]
Can you make one?

**Comment by kleinfreund** [comment]
@slonka Here you go: https://github.com/kumahq/kuma/issues/6658

**Comment by lahabana** [comment]
Duplicate of #696
