### ISSUE TITLE
Authentication type in Zone CP view

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-gui#424]
### What happened?

Authentication type in Zone CP view says "serviceAccountToken", which might indicate that the zone is using service account token to authenticate to global CP. When it reality it's DPPs that authenticate in this zone use serviceAccountToken.

**Comment by lahabana** [comment]
@jakubdyszkiewicz @kleinfreund I feel like this has been done no?

**Comment by kleinfreund** [comment]
I think so. We read data from the API in `src/utilities/helpers.ts:140` (`dpServer.auth.type` on subscription configs), so if that data is correct, the UI will display it.

**Comment by lahabana** [comment]
Right misunderstood this issue. It's about showing Zone auth not DPServer auth.

**Comment by lahabana** [comment]
On:

<img width="2713" alt="image" src="https://github.com/kumahq/kuma-gui/assets/702355/f041b3d0-4f07-4587-a366-52a62ffa87a8">

Instead of `Authentication type` let's name this `Dataplane authentication type` this will be clearer to users
