### ISSUE TITLE
Move OWNERS.md into kumahq/.github

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#426]
### Description

Issue for https://github.com/kumahq/kuma-gui/pull/413#discussion_r1005435519.

Move the OWNERS.md file into https://github.com/kumahq/.github so that it can be kept up-to-date more easily. The drawback is that the listed names won’t be project-specific anymore.

**Comment by kleinfreund** [comment]
@lahabana What should we do with the OWNERS.md file in the project? Also sync it from kumahq/.github?

**Comment by lahabana** [comment]
This is done now
