### ISSUE TITLE
The .sidebar-message-wrap is overlapping .menu-wrapper.last

### ISSUE THREAD

**Issue by scorsi** [kumahq/kuma-gui#43]
Hello :wave:

I'm running the kuma-gui on the last Firefox version on MacOS.

I can't see the 3 last elements of the menu, I have to delete or hidden the .sidebar-message-wrap to access them.

Here's a screenshot:
<img width="301" alt="Capture d’écran 2020-07-15 à 19 07 02" src="https://user-images.githubusercontent.com/8389441/87574246-68adba80-c6ce-11ea-9db3-ebafda535692.png">

Thanks,

**Comment by bloqhead** [comment]
Hello! 

Thanks for catching this. With the growing sidebar menu, this has become more of an issue lately. I've actually revised this in the latest version and have moved those resource links out of the sidebar as to avoid this altogether. My apologies for the inconvenience!

**Comment by scorsi** [comment]
Thanks ! I can close that issue so. :)
