### ISSUE TITLE
Display protocol with standard labels

### ISSUE THREAD

**Issue by mmorel-35** [kumahq/kuma-gui#443]
### Description

In `Mesh` > `Dataplanes Proxies`, in the column `protocol` we can see http or http2 or tcp as it is coming from kuma.io/protocol 
, it would be nice to use the standard labels, for example : 
- http => HTTP/1.1
- http2 => HTTP/2.0
- tcp => TCP

**Comment by slonka** [comment]
I think this is still relevant, removing stale.

**Comment by lukidzi** [comment]
@jakubdyszkiewicz is it the case with MeshService since there is a protocol field?

**Comment by jakubdyszkiewicz** [comment]
> Triage: We now have "<port>/<protocol>". It could be confusing to use slashes in protocol name
