### ISSUE TITLE
Auto-refresh every N seconds

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma-gui#452]
### Description

Could we implement an auto-refresh option in the GUI that automatically refreshes the data every N seconds, like:

<img width="881" alt="Screen Shot 2022-11-11 at 9 28 50 AM" src="https://user-images.githubusercontent.com/964813/201360726-1956a39a-e730-4745-aca7-d4e1c3887e64.png">

So when the user clicks the main "Refresh" button, it works as it is today. But if the user wants to choose to auto-refreshes, then we poll every N seconds. The auto-refresh can be disabled by clicking on "Once" again.

**Comment by lahabana** [comment]
Triage: There's multiple issues with this:

1. refresh causes things to move around
2. It's hard to figure when requests are potentially costly to the backend
3. Most of the data is pretty static so a refresh wouldn't be that useful
4. There are refresh buttons where refreshing things is already present
