### ISSUE TITLE
DPP view on small screens looks a bit crooked

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-gui#455]
### What happened?

A dpp view on a small screen looks a bit wonky to me.

<img width="1693" alt="image" src="https://user-images.githubusercontent.com/2753650/201876503-c1c7bbfd-36a4-4d8b-9b82-4e0344ea0e86.png">

A couple of things that "hurt my eye". 

![image](https://user-images.githubusercontent.com/2753650/201878484-925e1f6a-63bc-46e6-aa5c-234877ea9469.png)

Not really sure what's the best way to handle this, maybe just have first row 100% then 33% for the next 3 and then config with 100% like this:

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/2753650/201879131-263761ff-2228-4cf3-856f-b94c5182c1d2.png">

Or maybe just make sure that the config and insights are split 50/50 and the baseline is kept in sync?

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/2753650/201880980-b7621fb6-d1c0-466d-9165-476bd6d92139.png">

I'm up for suggestions.

**Comment by michaelbeaumont** [comment]
@kleinfreund is this still an issue? Has some redesign perhaps made this obsolete?

**Comment by kleinfreund** [comment]
@michaelbeaumont Yep, this has been addressed. We used to have 5 blocks of content that could easily lead to this seemingly misaligned 3 columns/2 columns layout shown above. Now it’s 3 blocks.

![image](https://user-images.githubusercontent.com/5774638/224343955-91ada3ff-f6d2-4789-ac9c-badf7135ae3c.png)
