### ISSUE TITLE
Service view should show the dataplanes that implement this service

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#463]
### Description

We now have `dataplane+insights?tags=kuma.io/service:foo` this way we can show all dataplanes that are attached to a service

**Comment by kleinfreund** [comment]
The `gateway`, `namePrefix`, and `tag` query parameters were implemented in https://github.com/kumahq/kuma/pull/5340.

**Comment by kleinfreund** [comment]
**Questions**:

1. Does adding this information make sense for both `ServiceInsight`s _and_ `ExternalService`s?
2. Do we want to …
   1. simply link to the data plane proxies attached to a service?
   2. link to the attached DPPs _and_ show additional information like the status of each DPP?

**Comment by lahabana** [comment]
This feature doesn't apply to external service (they are sensibly different). Yes to me  showing as much info as in the list all DPP view would be useful (My gut tells me this will be the favoured way for folks to find their DPP in the future)
