### ISSUE TITLE
Add Gateway view

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#464]
### Description

Add an entry in the sidebar that links to a page that shows the gateways `service+insights?gateway=true` for builtin gateways ability to drill in and see MeshGateways and MeshGatewayRoutes attached to it.

For the moment don't try to show the full builtin gateway just the policies attached to it. We can later think some more about a complex view but this is already a good first step.

**Comment by johncowen** [comment]
@lahabana just a note here after closing with a PR

> ability to drill in and see MeshGateways and MeshGatewayRoutes attached to it.

From what I understand I haven't done anything to cover that ^, but not totally sure if thats related to what philipp is working on, not sure if we want to create an extra issue off here to cover the fact that this bit of this issue isn't done as far as I'm aware?
