### ISSUE TITLE
Mesh in new policies YAML

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-gui#513]
### Description

![image](https://user-images.githubusercontent.com/5459824/208642069-5cdb5523-e810-4735-9061-0f9875b91470.png)

Mesh in the new policies on Kubernetes should look like this
```
metadata:
  labels:
    kuma.io/mesh: meshcircuitbreaker
```

**Comment by lahabana** [comment]
We should be able to do something much better for new policies (only the metadata varies now)

**Comment by lahabana** [comment]
#696 will move this to be server side (https://github.com/kumahq/kuma/issues/6658) therefore it will "just" work and this issue will be fixed as part of #696.

Therefore I'm closing this
