### ISSUE TITLE
When adding a zone failed to show zones

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#517]
### What happened?

on the GUI while a second zone was added the Zone http://localhost:5681/gui/zones failed with an error like:"cannot read property Some"

I guess the content of the zone response is unexpected.

**Comment by jakubdyszkiewicz** [comment]
> Triage:
> Deploy Global CP. Deploy Zone CP, refresh quickly, wait until Zone CP appears

**Comment by johncowen** [comment]
<img width="745" alt="Screenshot 2023-01-04 at 14 18 19" src="https://user-images.githubusercontent.com/554604/210574872-129e705f-aeb1-4d99-9d1e-566002022b26.png">

**Comment by lahabana** [comment]
The fix that was added was for dataplaneInsight while this issue is in MeshInsight are we sure this is the correct fix?

**Comment by johncowen** [comment]
I think so yeah, the same function is reused for both it's reused here in `ZonesView` https://github.com/kumahq/kuma-gui/blob/6e540fd433274ae6eaa39f5c849ce3e35ac1f4e5/src/app/zones/views/ZonesView.vue#L289 which was where it was erroring.

**Comment by lahabana** [comment]
Can we fix the type and parameter name then?
