### ISSUE TITLE
policies view improvement

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#542]
### What happened?

Some improvements to policy views are needed:

- clearer direction (from and to)
- Should “origin” be “policy”? (or “origin policy”?)
- “Origins” should be styled as a list
- Discuss with backend what needs to be done with the "on" column.

**Comment by kleinfreund** [comment]
## Should "Origins" be "Policies" or "Origin policies"?

I think "Origin policies" is the better term here.

## Origins should be presented as a list

Yes.

## Clearer direction (i.e. from/to or source/destination)

I need to know what’s currently unclear about the way "direction" is represented in the tables. 

## What should be done with the "On" column?

We should discuss this as a group while looking at the UI, preferably with a better set of mock data resembling a realistic application state with a decent amount of new policies.

**Comment by kleinfreund** [comment]
FYI if you want to look at how the view looks with the data provided by @lahabana in https://github.com/kumahq/kuma-gui/issues/542#issuecomment-1384110669, you can look at the deployment preview https://deploy-preview-551--kuma-gui.netlify.app/mesh/default/data-planes/backend which currently uses the rules structure from that gist.
