### ISSUE TITLE
Policy view for gateway doesn't show any policies applied for the gateway

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma-gui#590]
### Description

The policy view for the gateway doesn't show any policies applied for the gateway. It might require changes in API to return correct data.

**Comment by johncowen** [comment]
If I understand right, yeah its no longer the case.

Here's the view of what I think we are talking about (builtin and delegated)

![Screenshot 2024-04-05 at 14 42 03](https://github.com/kumahq/kuma-gui/assets/554604/5b74bc4a-4f2d-4bc3-992f-f4c7e01a165b)

![Screenshot 2024-04-05 at 14 42 56](https://github.com/kumahq/kuma-gui/assets/554604/827f9161-1438-4ff8-b2b0-9907e7a7bb23)
