### ISSUE TITLE
feat: Change wording of Status: not available

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#643]
### Description

Sometimes we display `Status: not available` which sounds a bit like the service itself is not available, not the fact that the status information is not available

We should word this a little better like maybe `Status: Information not available`

**Comment by svenwal** [comment]
@johnharris85 we have just spent ~1 hour with a customer trying to debug an external service which was shown as "not available" with all of us assuming this means backend not reachable. So the wording is very confusing and should be fixed
