### ISSUE TITLE
replace `import`s with injectable `use` equivalents

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#660]
### Description

Whilst reconfiguring some of the codebase to use a service container injection pattern, we hit a few places where it was more straightforwards to shim in the service injections via existing `import` due to the amount of instances of those imports throughout the codebase.

Now we have implemented as much service injection as we need to for the moment and the amount of service injection required is clearer, we should go back and make sure we use the same method for locating/using these services.

i.e. replace `import { thing }` with `useThing`

### Further details

There are at least 2 instances of this that immediately come to mind:

1. `kumaApi` Almost all usage of `kumaApi` currently uses the old `import { kumaApi }` which then uses a service container 'shim' (see below)

https://github.com/kumahq/kuma-gui/blob/dc34da7a77598fe1fc996abe112ff763643fd804/src/api/kumaApi.ts#L1-L2

2. `store` and `useStore`. Again both of these currently use the old `import { store, useStore }`. `store` is only imported in tests, but `useStore` is used throughout the application, both uses a small service container shim (see below)

https://github.com/kumahq/kuma-gui/blob/dc34da7a77598fe1fc996abe112ff763643fd804/src/store/store.ts#L6-L10

**Comment by slonka** [comment]
Seems to still be the case.

**Comment by johncowen** [comment]
Still the case I believe, although luckily it looks like we are slowly eating away at the old `store` and `kumaApi` code, so we are close to being able to do away with this entirely rebuilding things out. There maybe some `imports` still left that should be `use*`. We should check this before closing. Just to note, not sure what the priority is of doing this but it should be done at some point.
