### ISSUE TITLE
chore: replace instances of VITE_NAMESPACE, tagline etc with env('KUMA_*') equivalents

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#666]
### Description

During:

- https://github.com/kumahq/kuma-gui/pull/466
- https://github.com/kumahq/kuma-gui/pull/507
- https://github.com/kumahq/kuma-gui/pull/560

We added an `env` helper function to access non-changing/static 'environment variables'

We should replace all the various ways we used to access these variables with the new `env` helper.

Most of our "environment variables" are accessible via `env`, but over the past few weeks I have noticed that there are probably one or two more we need to add to `env`, this could be done as part of this task.

**Comment by slonka** [comment]
I still see "VITE_NAMESPACE" in the codebase so I'm assuming this is not stale. Please close if I'm mistaken.

**Comment by kleinfreund** [comment]
This still needs cleaning up. Removing VITE_NAMESPACE and KUMA_PRODUCT_NAME because of `const productName = encodeURIComponent(env('KUMA_PRODUCT_NAME'))` in `src/services/env/Env.ts`.
