### ISSUE TITLE
Always display policies in Universal and offer an option to copy it as k8s

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#696]
### Description

Who cares about kubernetes when you are using universal and vice-versa.

Let's just show the policies in the format of the global CP. 

Note that this is only for policies (mostly because policies are managed by the global CP). It might be trickier for dataplanes for example

**Comment by lahabana** [comment]
- Remove tabs
- Always show universal format
- add button next to the existing button to "copy in kubernetes format"

**Comment by jakubdyszkiewicz** [comment]
It's not a blocker. We can merge it without solving https://github.com/kumahq/kuma/issues/6780
