### ISSUE TITLE
Allow to hide some sections (especially extensions) in XDS Configuration

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-gui#910]
### Description

Whenever I'm looking at `XDS Configuration` I'm always wasting time scrolling down around half the screen (extensions take 1800 lines of the whole configuration) to go to the interesting me section. It would be awesome to be able to hide sections like `configs[0].bootstrap.extensions` or even whole `configs[0].bootstrap`.

**Comment by kleinfreund** [comment]
A couple of options:

- Easy, and perhaps good enough: move the less interesting sections of the XDS config towards its end (depending on the structure of this config, this might not be possible)
- Easy, but likely not good: in the backend, strip out those parts before when the request has some query parameter for that purpose (used by the UI)
- Very hard: add support for some kind of region collapsing feature to `KCodeBlock`. This would be very hard to implement. We’d only be able to do this on a per-language basis and would always need some sort of syntax tree to know where a "region" starts and ends.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's try the first solution

**Comment by lahabana** [comment]
Going to close this in favour of #1156
