### ISSUE TITLE
Go to next occurrence when hitting "enter" in search bar

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-gui#911]
### Description

It would be nice if when hitting "enter" in the search bar of the XDS Configuration, to go to the next occurrence of the searched text (maybe `shift + enter` to go to the previous one as well)
![image](https://github.com/kumahq/kuma-gui/assets/11655498/0eb36685-f9cd-41c7-a2ce-de58ae9c87a9)

**Comment by kleinfreund** [comment]
For the time being, this functionality currently has the shortcuts <kbd>F3</kbd> (next match) and <kbd>Shift+F3</kbd> (previous match).

Note that there is a possible risk of simply adding <kbd>Enter</kbd> and <kbd>Shift+Enter</kbd> for the same functionality (which itself is easy to do): when `KCodeBlock` is placed within a form, pressing <kbd>Enter</kbd> could lead to the form being submitted. While this is rare, as part of Kongponents, the code block component needs to take this into account.

**Comment by kleinfreund** [comment]
I’m proposing this change in https://github.com/Kong/kongponents/pull/1808.
